[package]
name = "cba-midi"
version = "0.1.0"
edition = "2021"

[dependencies]
midly = "0.5.3"

[dependencies.midir]
version = "0.9.1"
features = ["jack", "winrt"]

[dependencies.adw]
package = "libadwaita"
version = "0.5.3"
features = ["v1_2"]
