name: Compile CBA-Midi
on:
  release:
    types: [created]
  push:

jobs:
  release:
    name: release
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: msys2/setup-msys2@v2
        with:
          release: false
          update: true
          msystem: ucrt64
          pacboy: >-
            python:p
            meson:p
            ninja:p
            pkg-config:p
            rust:p
            blueprint-compiler:p
            gtk4:p

      - uses: actions/checkout@v3

      - name: Build CBA-midi
        run: |
          meson setup builddir --prefix=/
          meson compile -C builddir
          meson install -C builddir --destdir=release

      - name: Create Artifact
        run: |
          install -Dt release  /ucrt64/bin/{libiconv-2,libbz2-1,libcairo-2,libcairo-gobject-2,libcairo-script-interpreter-2,libepoxy-0,libexpat-1,libffi-8,libfontconfig-1,libfreetype-6,libfribidi-0,libgcc_s_seh-1,libgdk_pixbuf-2.0-0,libgio-2.0-0,libglib-2.0-0,libgmodule-2.0-0,libgobject-2.0-0,libgraphene-1.0-0,libgtk-4-1,libharfbuzz-0,libintl-8,libjpeg-8,libpango-1.0-0,libpangocairo-1.0-0,libpangoft2-1.0-0,libpangowin32-1.0-0,libpcre2-8-0,libpixman-1-0,libpng16-16,libtiff-6,libwinpthread-1,zlib1}.dll
          install -Dt release ./builddir/release/{bin/cba-midi.exe,share/cba-midi/{map.txt,cba-midi-resources.gresource}}
          

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: release/
      
